### ISSUE TITLE
Kolinahr crashes with URIError

### ISSUE THREAD

**Issue by sgallagher** [joeattardi/kolinahr#24]
```
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]: URIError: Failed to decode param '/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/winnt/win.ini'
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at decodeURIComponent (native)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at decode_param (/srv/kolinahr/node_modules/express/lib/router/layer.js:167:12)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at Layer.match (/srv/kolinahr/node_modules/express/lib/router/layer.js:143:15)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at matchLayer (/srv/kolinahr/node_modules/express/lib/router/index.js:557:18)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at next (/srv/kolinahr/node_modules/express/lib/router/index.js:216:15)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at initialize (/srv/kolinahr/node_modules/passport/lib/middleware/initialize.js:53:5)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at Layer.handle [as handle_request] (/srv/kolinahr/node_modules/express/lib/router/layer.js:95:5)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at trim_prefix (/srv/kolinahr/node_modules/express/lib/router/index.js:312:13)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at /srv/kolinahr/node_modules/express/lib/router/index.js:280:7
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at Function.process_params (/srv/kolinahr/node_modules/express/lib/router/index.js:330:12)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at next (/srv/kolinahr/node_modules/express/lib/router/index.js:271:10)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at jsonParser (/srv/kolinahr/node_modules/body-parser/lib/types/json.js:103:7)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at Layer.handle [as handle_request] (/srv/kolinahr/node_modules/express/lib/router/layer.js:95:5)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at trim_prefix (/srv/kolinahr/node_modules/express/lib/router/index.js:312:13)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at /srv/kolinahr/node_modules/express/lib/router/index.js:280:7
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at Function.process_params (/srv/kolinahr/node_modules/express/lib/router/index.js:330:12)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at next (/srv/kolinahr/node_modules/express/lib/router/index.js:271:10)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at SendStream.error (/srv/kolinahr/node_modules/serve-static/index.js:121:7)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at emitOne (events.js:96:13)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at SendStream.emit (events.js:188:7)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at SendStream.error (/srv/kolinahr/node_modules/send/index.js:275:17)
Mar 23 16:22:39 kolinahr.fedorainfracloud.org node[378]:     at SendStream.pipe (/srv/kolinahr/node_modules/send/index.js:479:10)
```

**Comment by joeattardi** [comment]
Possible fix explained here: http://stackoverflow.com/questions/36125216/express-handling-urierror-failed-to-decode-param
